apiVersion: batch/v1
kind: Job
metadata:
  name: traveny-db-migrate
  namespace: traveny
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: regcred
      containers:
      - name: db-migrate
        image: ghcr.io/maheshkmp/traveny/api:latest
        imagePullPolicy: Always
        command: ["bun", "run", "db:migrate"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: traveny-secrets
              key: database-url
