apiVersion: v1
kind: Secret
metadata:
  name: traveny-secrets
  namespace: traveny
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: postgrespassword
  postgres-db: traveny
  better-auth-secret: "replace-with-a-real-secret"
  resend-api-key: "re_replace_this"
  database-url: "postgresql://postgres:postgrespassword@db-service:5432/traveny"
